siteName: Los Armaños
siteDesc: Los armaños somos un motoclub familiar con capítulos en Jalisco y Querétaro. Nos gusta salir a rodar con quien sea y cuando sea. Si nos ves en el camino, salúdanos.
author:
  name: Zero
  site: zerothedragon.com
# pages:
#   Inicio: /
#   Noticias: /blog
cname: losarmanos.com
params:
  main: homepage
  styles: styles
